# source: https://github.com/open-webui/open-webui/blob/main/docker-compose.yaml
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - /root/docker-data/openwebui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
  pipelines-openwebui:
    build:
      context: .
      dockerfile: Dockerfile
    image: openwebui-pipelines:self
    ports:
      - 9099:9099
    environment:
      - REANA_SERVER_URL=https://reana-p4n.aip.de
    volumes:
      - /root/docker-data/pipelines-openwebui:/app/pipelines
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
 

